### ISSUE TITLE
SVG icons in header nav lost after Craft update to 3.0.7

### ISSUE THREAD

**Issue by marflow** [engram-design/CPNav#48]
Posted this originally at Craft github, but it seems to be a CP nav issue: After running Composer update to Craft 3.0.7 the icons in the dark blue area went missing. (Others were still present.)

Disabling the CP nav plugin brings back the icons so I am posting this here. Thank you vey much for checking that.

**Comment by adampatpattison** [comment]
I too am getting this. They briefly come back when changing a setting in the CP Nav settings area (as it refreshes) but disappears when you navigate away.

Is it to do with the changes to svg() functions in Craft 3.0.7?

**Comment by sergeifilippov** [comment]
Confirmed. Disabling the plugin returns the `icon-mask`

![5 promotions listing page - richmond mall 2018-05-17 11-19-17](https://user-images.githubusercontent.com/123676/40148817-3bfc24aa-59c4-11e8-881d-92a76063d85c.png)

**Comment by KatieMFritz** [comment]
Similar experience.
Enabled:
![screenshot-safs msu edu-2018 05 21-18-03-17](https://user-images.githubusercontent.com/7085184/40332227-46ac9910-5d21-11e8-84cd-69872ff34d48.png)


Disabled:
![screenshot-safs msu edu-2018 05 21-18-04-04](https://user-images.githubusercontent.com/7085184/40332239-646224d4-5d21-11e8-9ebe-1adb979d3783.png)

Additionally, when I try to upload custom SVGs for existing menu items, the displayed icon doesn't change.

**Comment by engram-design** [comment]
Fixed in [2.0.7](https://github.com/verbb/cp-nav/releases/tag/2.0.7)

**Comment by KatieMFritz** [comment]
@engram-design I just updated to 2.07 and I'm still seeing this bug. @sergeifilippov , you too?

![screenshot-safs local-2018 05 25-16-13-06](https://user-images.githubusercontent.com/7085184/40564402-924d9b5e-6036-11e8-8d25-be07e1b95c6f.png)
![screenshot-safs local-2018 05 25-16-13-25](https://user-images.githubusercontent.com/7085184/40564405-93588d4c-6036-11e8-9680-11362bacaf7b.png)

**Comment by engram-design** [comment]
Should be fixed in [2.0.8](https://github.com/verbb/cp-nav/releases/tag/2.0.8)
