### ISSUE TITLE
Lost icons

### ISSUE THREAD

**Issue by bartrylant** [engram-design/CPNav#50]
### Description
When Control Panel Nav is enabled, the default Craft icons in the left menu bar (dashboard, categories, users, utilities,...) become circles with letters.

### Additional info
- Plugin version: 2.0.7
- Craft version: 3.0.9

**Comment by lindseydiloreto** [comment]
I'm experiencing this too. The default icons are immediately lost when CP Nav is enabled.

**Comment by KatieMFritz** [comment]
Same. Related to #48. I really want to use this plugin but I'm worried that the missing icons hurt more than the custom links help. 🙁

**Comment by engram-design** [comment]
Should be fixed in [2.0.8](https://github.com/verbb/cp-nav/releases/tag/2.0.8)

**Comment by bartrylant** [comment]
2.0.8 didn't fix the issue for me. Globals, utilities, settings, categories, users and plugin store are still showing letters instead of icons. Dashboard, entries, assets are fine.

I tried clearing all the caches, but no change.

**Comment by engram-design** [comment]
You might need to regenerate the nav - go to CP Nav > Settings. You might also try uninstalling and reinstalling.

**Comment by bartrylant** [comment]
Yes, but then I have this issue: #51 
It doesn't fix it by the way.

Uninstalling the plugin en reinstalling did work.
